import { NELK, CHALLENGES, SOCIALGOOD, RESTAURANT, OFFICE } from './xchallenges';
import { DEFAULT } from './xquestions';

export const COMPANIES = [
    {
      "id": 0,
      "name": "PopTag",
      "bgcolor": '#F4FA58',
      "wordmark": 'ptlogored',
      "wordmarkoverlay": 'null',
      "icon": 'balloon',
      "iconoverlay": 'null',
      "shrinkicon": false,
      "iconalternate": 'null',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#FD3B00', '#4A90E2', '#4CAF50'],
      "questions": DEFAULT,
      "cover": 'poptagcover',
      "type": 'questions',
    },
    {
      "id": 1,
      "name": "Challenges",
      "bgcolor": 'thistle',
      "wordmark": 'null',
      "wordmarkoverlay": 'null',
      "icon": 'balloon',
      "iconoverlay": 'null',
      "shrinkicon": false,
      "iconalternate": 'null',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#63666A', '#115E67', '#003B5C', '#7A4183', '#ED8B00', '#CEDC00'],
      "questions": CHALLENGES,
      "cover": 'challengescover',
      "type": 'challenges',
    },
    {
      "id": 2,
      "name": "NELK",
      "bgcolor": '#3A82D6',
      "wordmark": 'nelklogo',
      "wordmarkoverlay": 'null',
      "icon": 'nelkicon',
      "iconoverlay": 'null',
      "shrinkicon": false,
      "iconalternate": 'nelkiconalternate',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#FBB23A', '#7EC242'],
      "questions": NELK,
      "cover": 'nelkcover',
      "type": 'challenges',
    },
    {
      "id": 3,
      "name": "Social Good",
      "bgcolor": 'random',
      "wordmark": 'null',
      "wordmarkoverlay": 'null',
      "icon": 'balloon',
      "iconoverlay": 'null',
      "shrinkicon": false,
      "iconalternate": 'null',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#FBB23A', '#7EC242'],
      "questions": SOCIALGOOD,
      "cover": 'socialgoodcover',
      "type": 'challenges',
    },
    {
      "id": 4,
      "name": "Office",
      "bgcolor": 'random',
      "wordmark": 'null',
      "wordmarkoverlay": 'null',
      "icon": 'balloon',
      "iconoverlay": 'null',
      "shrinkicon": false,
      "iconalternate": 'null',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#FBB23A', '#7EC242'],
      "questions": OFFICE,
      "cover": 'officecover',
      "type": 'challenges',
    },
    {
      "id": 5,
      "name": "Restaurant",
      "bgcolor": 'random',
      "wordmark": 'null',
      "wordmarkoverlay": 'null',
      "icon": 'balloon',
      "iconoverlay": 'null',
      "shrinkicon": false,
      "iconalternate": 'null',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#FBB23A', '#7EC242'],
      "questions": RESTAURANT,
      "cover": 'restaurantcover',
      "type": 'challenges',
    },
]