export const COMPANIES = [
    {
      "id": 0,
      "name": "PopTag",
      "bgcolor": '#F4FA58',
      "wordmark": 'ptlogored',
      "wordmarkoverlay": 'null',
      "icon": 'balloon',
      "iconoverlay": 'null',
      "shrinkicon": false,
      "iconalternate": 'null',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      //"palette": ['#FDB82A', '#F78119', '#E0393E', '#963D97', '#079CDB', '#62BA47'],
      "palette": ['#FD3B00', '#4A90E2', '#4CAF50'],
      "questions": 'DEFAULT',
      "missions": 'DEFAULT',
      "cover": 'poptagcover'
    },
    {
      "id": 1,
      "name": "Ultimate Software",
      "bgcolor": '#509E2F',
      "wordmark": 'ultimatesoftwarelogo',
      "wordmarkoverlay": '#FFFFFF',
      "icon": 'ultimatesoftwareicon',
      "iconoverlay": '#FFFFFF',
      "shrinkicon": true,
      "iconalternate": 'null',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#63666A', '#115E67', '#003B5C', '#7A4183', '#ED8B00', '#CEDC00'],
      "questions": 'DEFAULT',
      "missions": 'WLUHOCO',
      "cover": 'ultimatesoftwarecover'
    },
    {
      "id": 2,
      "name": "NELK",
      "bgcolor": '#4A90E2',
      "wordmark": 'nelklogo',
      "wordmarkoverlay": 'null',
      "icon": 'nelkicon',
      "iconoverlay": 'null',
      "shrinkicon": false,
      "iconalternate": 'nelkiconalternate',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#FBB23A', '#7EC242'],
      "questions": 'DEFAULT',
      "missions": 'WLUHOCO',
      "cover": 'nelkcover'
    },
]