export const COMPANIES = [
    {
      "id": 0,
      "name": "PopTag",
      "bgcolor": '#F4FA58',
      "wordmark": 'ptlogored',
      "wordmarkoverlay": 'null',
      "icon": 'balloon',
      "iconoverlay": 'null',
      "shrinkicon": false,
      "iconalternate": 'null',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#FD3B00', '#4A90E2', '#4CAF50'],
      "questions": 'DEFAULT',
      "cover": 'poptagcover',
      "type": 'questions',
      //"missions": 'DEFAULT',
    },
    {
      "id": 1,
      "name": "Ultimate Software",
      "bgcolor": '#509E2F',
      "wordmark": 'ultimatesoftwarelogo',
      "wordmarkoverlay": '#FFFFFF',
      "icon": 'balloon',
      "iconoverlay": '#FFFFFF',
      "shrinkicon": true,
      "iconalternate": 'ultimatesoftwareicon',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#63666A', '#115E67', '#003B5C', '#7A4183', '#ED8B00', '#CEDC00'],
      "questions": 'DEFAULT',
      "cover": 'ultimatesoftwarecover',
      "type": 'questions',
      //"missions": 'WLUHOCO',
    },
    {
      "id": 2,
      "name": "NELK",
      "bgcolor": '#3A82D6',
      "wordmark": 'nelklogo',
      "wordmarkoverlay": 'null',
      "icon": 'nelkicon',
      "iconoverlay": 'null',
      "shrinkicon": false,
      "iconalternate": 'nelkiconalternate',
      "iconalternateoverlay": 'null',
      "shrinkiconalternate": true,
      "palette": ['#FBB23A', '#7EC242'],
      "questions": 'NELK',
      "cover": 'nelkcover',
      "type": 'challenges',
      //"missions": 'WLUHOCO',
    },
]