# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PopTag' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PopTag
  pod 'RNInstagramStoryShare', :path => '../node_modules/react-native-instagram-story-share/ios'

  pod 'React', :path => '../node_modules/react-native'

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'RNShare', :path => '../node_modules/react-native-share'

target 'PopTagTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PopTag-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PopTag-tvOS

  target 'PopTag-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end


  end
end